name: 提出问题寻求解答
description: 向开发者/其他用户表达您的疑惑并寻求帮助
title: '[Question] '
labels: [question,help wanted]
body:
  - type: markdown
    attributes:
      value: |
        来提问吧～
  - type: input
    id: python-version
    attributes:
      label: Python 版本
      description: 可通过 `python --version` 命令查看
      placeholder: "3.12"
    validations:
      required: true
  - type: input
    id: SuggarChat-version
    attributes:
      label: SuggarChat 版本
      description: 在插件启动后会输出（如果没有成功启动可不填）
      placeholder: 1.9.0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: 您遇到了什么问题？
      description: 填写你遇到的问题
    validations:
      required: true
  - type: textarea
    id: SuggarChat-log
    attributes:
      label: SuggarChat 运行日志
      description: 请粘贴插件运行后报错的控制台内容到此，如果您认为这有帮助。
      render: shell
    validations:
      required: false
